apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eshop-api
    dce.daocloud.io/app: eshop-api
  name: eshop-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-api
  template:
    metadata:
      labels:
        app: eshop-api
        dce.daocloud.io/app: eshop-api
      name: eshop-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - image: 10.7.106.172/kube-system/dotnet-eshop-api:1.0.4
        imagePullPolicy: IfNotPresent
        name: eshop-api
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: "509715200"
          requests:
            cpu: 500m
            memory: "509715200"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    dce.daocloud.io/app: eshop-api
  name: eshop-api
spec:
  ports:
  - nodePort: 33862
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: eshop-api
  type: NodePort